### PR TITLE
BD Layer test code Improvement

### PR DESCRIPTION
**Pull request by kishoreandukuri**
Did test code developemnt for the methods SelectAll_DSQL, SelectAll_DR, Select, Insert, Update and Delete in BDLayer

### CODE REVIEW

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Change of #121 is mixed.
The actual change is the following two files.
- root/programs/C#/Tests/BDLayer.Test/BDLayer.Test.nunit
- root/programs/C#/Tests/BDLayer.Test/CRUDTest.cs 

Please tell us the acceptance plan for this pullrequest.

To check the execution results using Jenkins of this code,
There is a need to merge to the repository.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please send evidence of all-green of NUNIT to IP server.
If so, this pull request will be merged.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
This pullrequest has been sent to the develop branch of OpenTouryoProject/OpenTouryo,
but this pullrequest should be sent to the nishino branch of SymphonyTeleca/OpenTouryo.

@yusukemaegawa 
I think that there is no problem about this evidence.
Please do merge or ask the sending of pullrequest in via nishino branch.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
This pullrequest has been sent to the develop branch of OpenTouryoProject/OpenTouryo,
but this pullrequest should be sent to the nishino branch of SymphonyTeleca/OpenTouryo.

Also the according to [recent survey results](https://github.com/OpenTouryoProject/OpenTouryo/issues/101#issuecomment-152919083), the rollback problem maybe does not occur.
Therefor, it does not seem necessary to include two changes to the two pull request that have time difference.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
As per the indications in GitHub,
https://github.com/OpenTouryoProject/OpenTouryo/issues/114

>Please send the pullrequest to OpenTouryoProject/OpenTouryou's develop branch.

we created pull request into develop branch of OpenTouryoProject/OpenTouryo

we will again create new pull request to nishino branch of SymphonyTeleca/OpenTouryo and send for your review.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>we will again create new pull request to nishino branch of SymphonyTeleca/OpenTouryo and send for your review.

Yes, please do so.
Basically all pullrequest go through the nishino branch.

>We don't need to include the code changes of pull request #121 in this pull request #122 

Yes, do not need to include.
Since the rollback(revert) problem does not occur.

>Shall we create pull request with only pull request #122 changes to nishino branch of SymphonyTeleca/OpenTouryo?

Yes, please.

However, there seems to be pointed out.
https://github.com/OpenTouryoProject/OpenTouryo/pull/123#discussion_r43836906

**Pull request closed without merging**
