### PR TITLE
Fixed : "The debug of website e.g. : "ProjectX_sample" in "root_VS2013" fails." #12

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/12
see : https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/39

##### CSharp
- https://github.com/SymphonyTeleca/OpenTouryo/pull/101

##### VB
- https://github.com/SymphonyTeleca/OpenTouryo/pull/102

### Additional modifications
- https://github.com/SymphonyTeleca/OpenTouryo/pull/104

### CODE REVIEW

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I found a leak of only one merge by comparing the following two.
- https://github.com/SymphonyTeleca/OpenTouryo/tree/nishino/root
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino/root_VS2013


Please check the following.
- https://github.com/SymphonyTeleca/OpenTouryo/tree/nishino/root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/nest/testScreen1nest.aspx.vb#L736
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino/root_VS2013/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/nest/testScreen1nest.aspx.vb#L736

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Why aren't there **TMProtocolDefinition2.xml** in "file changes" of this pull request?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Because it does not require the two definitions in the version of less than VS2013.
Therefore, root of VS2010 is not required "TMProtocolDefinition2.xml".

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>Because it does not require the two definitions in the version of less than VS2013.
>Therefore, root of VS2010 is not required "TMProtocolDefinition2.xml".

Where do you specify that the target version of Visual Studio in this repository is 2010 or 2012?
If you describe in nowhere, please add description in somewhere.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I have described in the following points.
https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/README.md

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I think that you should describe develop/run-time environment in the top of readme.

e.g.
# Open棟梁(OpenTouryo)
”Open棟梁”は、長年の.NETアプリケーション開発実績にて蓄積したノウハウに基づき開発した.NET用アプリケーション フレームワークです。
(”OpenTouryo” , is an application framework for .NET which was developed using the accumulated know-how with a long track record in .NET application development.)

## 開発／動作環境(develop/run-time environment)
このリポジトリのプログラムは、サポートされる最も古い開発／実行環境を使用して開発しています。 (I am developing the program of this repository, using the oldest supported develop/run-time environment.)
- 開発環境 (develop environment)
    - Visual Studio 2010
- 実行環境 (run-time environment)
    - .NET Framework 3.5 SP1

Visual Studio 2015 など、新しい開発環境を使用する場合は、[テンプレート・ベース](https://github.com/OpenTouryoProject/OpenTouryoTemplates)を参照してください。 (If you want to use the latest develop environment (e.g. Visual Studio 2015), please refer [Templates base](https://github.com/OpenTouryoProject/OpenTouryoTemplates).)

## 概要(summary)
以下のファイルを参照してください。
(Please refer to the following files.)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Thank you for your proposed.
Please check, because I modified it as follows.
- https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/README.md
- https://github.com/OpenTouryoProject/OpenTouryo/pull/159/files#diff-04c6e90faac2675aa89e2176d2eec7d8L1

Please merge as soon as possible.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I solved the conflict by revert. Please merge.

**Pull request merged**
