### PR TITLE
Fixed : "Some of the problem of asynchronous processing service are found at the acceptance." #164

### LINKED ISSUE #164: Some of the problem of asynchronous processing service are found at the acceptance.
# Report problems

##### Connection String
The default value of this project is the following.
```
Data Source=localhost\sqlexpress;Integrated Security=SSPI;Initial Catalog=AsyncProcessingServiceDB;
```

The following settings have a problem of different from default value.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/app.config
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config

##### XML definition
The default value should be set with the sample program rather than **"azure strage copy"**.

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMProtocolDefinition.xml#L30
```
<Transmission id="AzureStrageCopy" protocol="1"/>
```
▼ ▼ ▼
```
<Transmission id="AsyncSvc_sample" protocol="1"/>
```

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMInProcessDefinition.xml
```
<Transmission id="AsyncSvcSample" assemblyName="AsyncSvc_sample" className="AsyncSvcSample.LayerB" />
```

### Behavior
If there is a problem with the connection string,
then the following behavior was showed.

Modify the program by analyze the problem.

##### Start Service
This service would be started successfully from the SCM.
- It should fail to start.

##### Stop Service
In addition, This service could not be stopped from the SCM.
- Do not fail to stop.

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #164 

- [Implemented code to modify the behaviour of start and stop service. #128](https://github.com/SymphonyTeleca/OpenTouryo/pull/128)
- [Modified AsyncProcess sample to respond to various test cases. #129](https://github.com/SymphonyTeleca/OpenTouryo/pull/129)

### CODE REVIEW

**Comment by daisukenishino** [comment]
@SandeepNayak077 

We did not discover any problems by performing the reviews.
Please tell me one thing, does this fix has been tested ?
If so, this pullrequest will be merged.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Yes we have successfully tested all required scenarios for this issue.
There is no problem, you can merge the pull request.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I see.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

I found that the below condition was missed during the code commit [here](https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L236).
```CS
if (this._isServiceException)
```` 
↓ ↓ ↓
```CS
if (!this._isServiceException)
```` 
Please merge the [pull request#113](https://github.com/SymphonyTeleca/OpenTouryo/pull/133).

I am sorry for the inconvenience.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>https://github.com/OpenTouryoProject/OpenTouryo/pull/180#issuecomment-228274278

All's well that ends well.
Please check with a sufficient test that the problem is gone.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

>https://github.com/OpenTouryoProject/OpenTouryo/pull/180#issuecomment-228275259

Thank you for your support.
We retested all test cases and uploaded the evidences in **IPS: /Delivery/20160624/**
It is confirmed that there is no problem.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I see.

**Pull request merged**
