### PR TITLE
Fixed : "Converting a Web Site Project to a Web Application Project." #173

### LINKED ISSUE #173: Converting a Web Site Project to a Web Application Project.
# Requirement
ProjectX_sample has been created as a WebSite of ASP.NET WebForms.
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample

### Recommend Web application
Microsoft seems to recommend web application for the new development using Visual Studio after 2012. Therefore, I want to change the Web site to the Web application at root folder.

- Web Application Projects versus Web Site Projects in Visual Studio  
https://msdn.microsoft.com/en-us/library/dd547590.aspx
  - For new development, we recommend that you choose web application projects.
  - For example, the next Visual Studio release after Visual Studio 2012 will have new tooling for creating web projects, and this new tooling will work only with web application projects.

### About mixture of MVC and WebAPI
Do not mix because it become difficult to understand.

### Reference
- Walkthrough: Converting a Web Site Project to a Web Application Project in Visual Studio  
https://msdn.microsoft.com/en-us/library/aa983476.aspx
- ASP.NET構成（Webサイト・Webアプリ） - マイクロソフト系技術情報 Wiki  
ASP.NETアプリケーションの種類について > 回答 > 選択の観点  
http://techinfoofmicrosofttech.osscons.jp/index.php?ASP.NET%E6%A7%8B%E6%88%90%EF%BC%88Web%E3%82%B5%E3%82%A4%E3%83%88%E3%83%BBWeb%E3%82%A2%E3%83%97%E3%83%AA%EF%BC%89#md58660b

### PR DESCRIPTION
**Pull request by daisukenishino**
Fixed #173 
- [Converted ProjectX_sample website to webapp #125
](https://github.com/SymphonyTeleca/OpenTouryo/pull/125)
  - [Resolved the conflict of Converted ProjectX_sample website to webapp #136](https://github.com/SymphonyTeleca/OpenTouryo/pull/136)
- [Changed webapp version from 4.0 to 3.5 as per review comment. #139](https://github.com/SymphonyTeleca/OpenTouryo/pull/139)

### CODE REVIEW

**Comment by daisukenishino** [comment]
@yusukemaegawa 

This is pull-requests that is sent from the branch after eliminating the conflict.
Please confirm and merge.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

You set TargetFrameworkVersion property of new web application project to *v4.0*.
https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/ProjectX_sample.csproj#L15

But, in OpenTouryo repository, target framework version of OpenTouryo Framework is *v3.5*.
And you set this property of other samples to *v3.5*.

So, I propose that you set TargetFrameworkVersion property of new web application project to *v3.5*.

**Comment by daisukenishino** [comment]
@supragyan 

- Correct this ( v4.0 ---> v3.5).
- Check operation and perform test.
- Send a pull-request to nishino branch.

**Comment by supragyan** [comment]
@daisukenishino 

We have changed the ProjectX_Sample webapp version from 4.0 to 3.5.
And created pull request as [#139](https://github.com/SymphonyTeleca/OpenTouryo/pull/139)

Please review and merge.

**Comment by daisukenishino** [comment]
@yusukemaegawa

Please confirm and merge.

**Pull request merged**
