### PR TITLE
I deleted root_easysetup dir contents.

### PR DESCRIPTION
**Pull request by daisukenishino2**
Target repository is /SymphonyTeleca/OpenTouryo/.
- Create feature branch here, and delete root_easysetup dir contents, and commit.
- And, send pull request to nishino branch from above feature branch.

### CODE REVIEW

**Comment by daisukenishino** [comment]
@yusukemaegawa 
This pullrequest is due to this https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/23#issuecomment-171914767.

@kishoreandukuri 
Conflict has occurred, but can't you resolve this by modifying the nishino branch ?
Did you make the "root_easysetup_Deleted" feature branch from nishino branch ?

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Conflict has occurred, but can't you resolve this by modifying the nishino branch ?

We have created feature branch from nishino branch.
At the time of pull request creation no conflicts occurred.
May be later because of code changes conflicts occurred

>Did you make the "root_easysetup_Deleted" feature branch from nishino branch ?
Yes

Shall we create feature branch again from nishino branch ?

Please let us know

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>Shall we create feature branch again from nishino branch ?

I think that it is meaningless.
There is a need to resolve the conflict between the two branch.
Tomorrow, we will try to resolve this conflict.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Tomorrow, we will try to resolve this conflict.
Please let us know if anything needed from our side.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

I solved the conflict in accordance with the following instructions that is presented by Github.

### Checkout via command line
If you cannot merge a pull request automatically here, you have the option of checking it out via command line to resolve conflicts and perform a manual merge.

https://github.com/SymphonyTeleca/OpenTouryo.git

#### Step 1: From your project repository, check out a new branch and test the changes.
```
git checkout -b SymphonyTeleca-nishino develop
git pull https://github.com/SymphonyTeleca/OpenTouryo.git nishino
```
#### Step 2: Merge the changes and update on GitHub.
```
git checkout develop
git merge --no-ff SymphonyTeleca-nishino
git push origin develop
```

### Actual executed command.
It is status that https://github.com/OpenTouryoProject/OpenTouryo.git has been cloned at path of "/c/OpenTouryo/" by TortoiseGit. And, the following is a command that was actually executed by Git Bash.
```
$ cd /c/OpenTouryo/
$ git checkout -b SymphonyTeleca-nishino develop
$ git pull https://github.com/SymphonyTeleca/OpenTouryo.git nishino
$ git checkout develop
$ git status
$ git rm root_easysetup/programs/C#/z_Common2.bat
$ git rm root_easysetup/programs/VB/z_Common2.bat
$ git status
$ git commit
$ git checkout develop
$ git merge --no-ff SymphonyTeleca-nishino
$ git push origin develop
```

**Pull request merged**
